services:
  flutter:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - .:/app
      - flutter-data:/home/developer/flutter
    ports:
      - "8080:8080"
    user: "${UID:-1000}:${GID:-1000}"
    tty: true
    stdin_open: true

volumes:
  flutter-data: