name: mon_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  table_calendar: ^3.1.0
  sqflite: ^2.3.2
  path: ^1.8.3
  uuid: ^4.3.3
  speech_to_text: ^6.5.1
  permission_handler: ^11.1.0  # Pour gérer les permissions du microphone
  http: ^1.1.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env